export const LANGUAGES: Record<string, string> = {
	ARABIC: 'ar',
	AMHARIC: 'am',
	BASQUE: 'eu',
	BENGALI: 'bn',
	BULGARIAN: 'bg',
	CATALAN: 'ca',
	CHEROKEE: 'chr',
	CHINESE_PRC: 'zh-CN',
	CHINESE_TAIWAN: 'zh-TW',
	CROATIAN: 'hr',
	CZECH: 'cs',
	DANISH: 'da',
	DUTCH: 'nl',
	ENGLISH_UK: 'en-GB',
	ENGLISH_US: 'en',
	ESTONIAN: 'et',
	FILIPINO: 'fil',
	FINNISH: 'fi',
	FRENCH: 'fr',
	GERMAN: 'de',
	GREEK: 'el',
	GUJARATI: 'gu',
	HEBREW: 'iw',
	HINDI: 'hi',
	HUNGARIAN: 'hu',
	ICELANDIC: 'is',
	INDONESIAN: 'id',
	ITALIAN: 'it',
	JAPANESE: 'ja',
	KANNADA: 'kn',
	KOREAN: 'ko',
	LATVIAN: 'lv',
	LITHUANIAN: 'lt',
	MALAY: 'ms',
	MALAYALAM: 'ml',
	MARATHI: 'mr',
	NORWEGIAN: 'no',
	POLISH: 'pl',
	PORTUGUESE_BRAZIL: 'pt-BR',
	PORTUGUESE_PORTUGAL: 'pt-PT',
	ROMANIAN: 'ro',
	RUSSIAN: 'ru',
	SERBIAN: 'sr',
	SLOVAK: 'sk',
	SLOVENIAN: 'sl',
	SPANISH: 'es',
	SWAHILI: 'sw',
	SWEDISH: 'sv',
	TAMIL: 'ta',
	TELUGU: 'te',
	THAI: 'th',
	TURKISH: 'tr',
	UKRAINIAN: 'uk',
	URDU: 'ur',
	VIETNAMESE: 'vi',
	WELSH: 'cy'
};

export const LANGUAGE_CODES: Record<string, string> = {
	am: 'Amharic',
	ar: 'Arabic',
	bg: 'Bulgarian',
	bn: 'Bengali',
	ca: 'Catalan',
	chr: 'Cherokee',
	cs: 'Czech',
	cy: 'Welsh',
	da: 'Danish',
	de: 'German',
	el: 'Greek',
	en: 'English (US)',
	'en-GB': 'English (UK)',
	et: 'Estonian',
	eu: 'Basque',
	fi: 'Finnish',
	fil: 'Filipino',
	fr: 'French',
	gu: 'Gujarati',
	hi: 'Hindi',
	hr: 'Croatian',
	hu: 'Hungarian',
	id: 'Indonesian',
	is: 'Icelandic',
	it: 'Italian',
	iw: 'Hebrew',
	ja: 'Japanese',
	kn: 'Kannada',
	ko: 'Korean',
	lt: 'Lithuanian',
	lv: 'Latvian',
	ml: 'Malayalam',
	mr: 'Marathi',
	ms: 'Malay',
	nl: 'Dutch',
	no: 'Norwegian',
	pl: 'Polish',
	'pt-BR': 'Portuguese (Brazil)',
	'pt-PT': 'Portuguese (Portugal)',
	ro: 'Romanian',
	ru: 'Russian',
	sk: 'Slovak',
	sl: 'Slovenian',
	sr: 'Serbian',
	es: 'Spanish',
	sv: 'Swedish',
	sw: 'Swahili',
	ta: 'Tamil',
	te: 'Telugu',
	th: 'Thai',
	tr: 'Turkish',
	uk: 'Ukrainian',
	ur: 'Urdu',
	vi: 'Vietnamese',
	'zh-CN': 'Chinese (PRC)',
	'zh-TW': 'Chinese (Taiwan)'
};