RichEditor.ILC.Register('en-GB', {
	'apply': 'Apply',
	'cancel': 'Cancel',
	'colorpicker': 'Colour Picker',
	'confirm': 'Confirm',
	'counter.total': 'Total',
	'counter.words': 'Words',
	'format.Indent': 'Indent',
	'format.Outdent': 'Outdent',
	'format.alignCenter': 'Align centre',
	'format.alignJustify': 'Justify',
	'format.alignLeft': 'Align left',
	'format.alignRight': 'Align right',
	'format.backColor': 'Back colour',
	'format.blockquote': 'Blockquote',
	'format.bold': 'Bold',
	'format.code': 'Code',
	'format.color.default': 'Default colour',
	'format.div': 'Div',
	'format.font.default': 'Default Font',
	'format.fontFamily': 'Font Family',
	'format.fontSize': 'Font Size',
	'format.heading1': 'Heading 1',
	'format.heading2': 'Heading 2',
	'format.heading3': 'Heading 3',
	'format.heading4': 'Heading 4',
	'format.heading5': 'Heading 5',
	'format.heading6': 'Heading 6',
	'format.italic': 'Italic',
	'format.normal': 'Normal',
	'format.paragraph': 'Paragraph',
	'format.pre': 'Pre',
	'format.strikethrough': 'Strikethrough',
	'format.subscript': 'Subscript',
	'format.superscript': 'Superscript',
	'format.textColor': 'Text colour',
	'format.underline': 'Underline',
	'insert': 'Insert',
	'more': 'More',
	'plugins.link.insert': 'Insert a link',
	'plugins.link.title': 'Insert/Edit a link',
	'plugins.link.update': 'Update the link',
	'plugins.lists.bullet': 'Bulleted List',
	'plugins.lists.number': 'Numbered List',
	'plugins.media.image.insert': 'Insert an image via URL',
	'plugins.media.image.title': 'Insert/Upload an image',
	'plugins.media.image.update': 'Update the image URL',
	'plugins.media.insert': 'Insert a media via URL',
	'plugins.media.title': 'Insert/Edit a media',
	'plugins.media.update': 'Update the media URL',
	'plugins.table.title': 'Create a table',
	'plugins.parts.menu.alignCenter': 'Align centre with text break',
	'plugins.parts.menu.alignLeft': 'Align left with text break',
	'plugins.parts.menu.alignRight': 'Align right with text break',
	'plugins.parts.menu.floatLeft': 'Align left with text wrapping',
	'plugins.parts.menu.floatRight': 'Align right with text wrapping',
	'plugins.parts.menu.remove.figure': 'Remove the figure',
	'plugins.parts.menu.table.alignment': 'Align a table',
	'plugins.parts.menu.table.column': 'Table column',
	'plugins.parts.menu.table.column.delete': 'Delete column',
	'plugins.parts.menu.table.column.insert.left': 'Insert column left',
	'plugins.parts.menu.table.column.insert.right': 'Insert column right',
	'plugins.parts.menu.table.column.select': 'Select column',
	'plugins.parts.menu.table.move': 'Move a table',
	'plugins.parts.menu.table.row': 'Table Row',
	'plugins.parts.menu.table.row.delete': 'Delete row',
	'plugins.parts.menu.table.row.insert.above': 'Insert row above',
	'plugins.parts.menu.table.row.insert.below': 'Insert row below',
	'plugins.parts.menu.table.row.select': 'Select row',
	'remove': 'Remove',
	'toolbar.horizontal.line': 'Horizontal line',
	'toolbar.info': 'Information',
	'toolbar.redo': 'Redo',
	'toolbar.select.all': 'Select all',
	'toolbar.shortcuts': 'Shortcuts',
	'toolbar.undo': 'Undo',
	'update': 'Update'
});