import Editor from '../Editor';

export enum ENativeEvents {
	abort = 'abort',
	animationcancel = 'animationcancel',
	animationend = 'animationend',
	animationiteration = 'animationiteration',
	animationstart = 'animationstart',
	auxclick = 'auxclick',
	beforeinput = 'beforeinput',
	blur = 'blur',
	cancel = 'cancel',
	canplay = 'canplay',
	canplaythrough = 'canplaythrough',
	change = 'change',
	click = 'click',
	close = 'close',
	compositionend = 'compositionend',
	compositionstart = 'compositionstart',
	compositionupdate = 'compositionupdate',
	contextmenu = 'contextmenu',
	copy = 'copy',
	cuechange = 'cuechange',
	cut = 'cut',
	dblclick = 'dblclick',
	drag = 'drag',
	dragend = 'dragend',
	dragenter = 'dragenter',
	dragleave = 'dragleave',
	dragover = 'dragover',
	dragstart = 'dragstart',
	drop = 'drop',
	durationchange = 'durationchange',
	emptied = 'emptied',
	ended = 'ended',
	error = 'error',
	focus = 'focus',
	focusin = 'focusin',
	focusout = 'focusout',
	formdata = 'formdata',
	gotpointercapture = 'gotpointercapture',
	input = 'input',
	invalid = 'invalid',
	keydown = 'keydown',
	keypress = 'keypress',
	keyup = 'keyup',
	load = 'load',
	loadeddata = 'loadeddata',
	loadedmetadata = 'loadedmetadata',
	loadstart = 'loadstart',
	lostpointercapture = 'lostpointercapture',
	mousedown = 'mousedown',
	mouseenter = 'mouseenter',
	mouseleave = 'mouseleave',
	mousemove = 'mousemove',
	mouseout = 'mouseout',
	mouseover = 'mouseover',
	mouseup = 'mouseup',
	paste = 'paste',
	pause = 'pause',
	play = 'play',
	playing = 'playing',
	pointercancel = 'pointercancel',
	pointerdown = 'pointerdown',
	pointerenter = 'pointerenter',
	pointerleave = 'pointerleave',
	pointermove = 'pointermove',
	pointerout = 'pointerout',
	pointerover = 'pointerover',
	pointerup = 'pointerup',
	progress = 'progress',
	ratechange = 'ratechange',
	reset = 'reset',
	resize = 'resize',
	scroll = 'scroll',
	securitypolicyviolation = 'securitypolicyviolation',
	seeked = 'seeked',
	seeking = 'seeking',
	select = 'select',
	selectionchange = 'selectionchange',
	selectstart = 'selectstart',
	slotchange = 'slotchange',
	stalled = 'stalled',
	submit = 'submit',
	suspend = 'suspend',
	timeupdate = 'timeupdate',
	toggle = 'toggle',
	touchcancel = 'touchcancel',
	touchend = 'touchend',
	touchmove = 'touchmove',
	touchstart = 'touchstart',
	transitioncancel = 'transitioncancel',
	transitionend = 'transitionend',
	transitionrun = 'transitionrun',
	transitionstart = 'transitionstart',
	volumechange = 'volumechange',
	waiting = 'waiting',
	webkitanimationend = 'webkitanimationend',
	webkitanimationiteration = 'webkitanimationiteration',
	webkitanimationstart = 'webkitanimationstart',
	webkittransitionend = 'webkittransitionend',
	wheel = 'wheel',
}

export enum EInputEventType {
	insertText = 'insertText',
	insertReplacementText = 'insertReplacementText',
	insertLineBreak = 'insertLineBreak',
	insertParagraph = 'insertParagraph',
	insertOrderedList = 'insertOrderedList',
	insertUnorderedList = 'insertUnorderedList',
	insertHorizontalRule = 'insertHorizontalRule',
	insertFromYank = 'insertFromYank',
	insertFromDrop = 'insertFromDrop',
	insertFromPaste = 'insertFromPaste',
	insertTranspose = 'insertTranspose',
	insertCompositionText = 'insertCompositionText',
	insertFromComposition = 'insertFromComposition',
	insertLink = 'insertLink',
	deleteByComposition = 'deleteByComposition',
	deleteCompositionText = 'deleteCompositionText',
	deleteWordBackward = 'deleteWordBackward',
	deleteWordForward = 'deleteWordForward',
	deleteSoftLineBackward = 'deleteSoftLineBackward',
	deleteSoftLineForward = 'deleteSoftLineForward',
	deleteEntireSoftLine = 'deleteEntireSoftLine',
	deleteHardLineBackward = 'deleteHardLineBackward',
	deleteHardLineForward = 'deleteHardLineForward',
	deleteByDrag = 'deleteByDrag',
	deleteByCut = 'deleteByCut',
	deleteByContent = 'deleteByContent',
	deleteContentBackward = 'deleteContentBackward',
	deleteContentForward = 'deleteContentForward',
	historyUndo = 'historyUndo',
	historyRedo = 'historyRedo',
	formatBold = 'formatBold',
	formatItalic = 'formatItalic',
	formatUnderline = 'formatUnderline',
	formatStrikethrough = 'formatStrikethrough',
	formatSuperscript = 'formatSuperscript',
	formatSubscript = 'formatSubscript',
	formatJustifyFull = 'formatJustifyFull',
	formatJustifyCenter = 'formatJustifyCenter',
	formatJustifyRight = 'formatJustifyRight',
	formatJustifyLeft = 'formatJustifyLeft',
	formatIndent = 'formatIndent',
	formatOutdent = 'formatOutdent',
	formatRemove = 'formatRemove',
	formatSetBlockTextDirection = 'formatSetBlockTextDirection',
	formatSetInlineTextDirection = 'formatSetInlineTextDirection',
	formatBackColor = 'formatBackColor',
	formatFontColor = 'formatFontColor',
	formatFontName = 'formatFontName',
}

export interface IEventSetupCallback<K extends keyof GlobalEventHandlersEventMap> {
	(editor: Editor, event: GlobalEventHandlersEventMap[K]): void;
}

export const Setup = <K extends keyof GlobalEventHandlersEventMap>(editor: Editor, eventName: K, event: IEventSetupCallback<K>) =>
	editor.On(eventName, (evt: GlobalEventHandlersEventMap[K]) => event(editor, evt));

export const PreventEvent = (event: Event) => {
	event.preventDefault();
	event.stopImmediatePropagation();
	event.stopPropagation();
};